codecov:
  notify:
    require_ci_to_pass: true

ignore:
  - "tests/*"

coverage:
  precision: 2
  round: nearest
  range: "70...100"

  status:
    project: true
    patch: false
    changes: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
