#!/bin/bash

################################################################################
# LocalAlias                                                                   #
#                                                                              #
# Allows you to create and use aliases and functions that are local to the     #
# directory that they were created in.                                         #
################################################################################
    
LOCALALIAS_FILE="./.lshrc"

read -d '' awkScript <<-'EOF'
BEGIN { 
    printf "set -- %s\\n", args
}
$0 ~ my_func " ()" {flag=1; next}
/^}$/{flag=0} 
{
    if (flag) {
        gsub(/  [ ]*/, "")
        print $0
    }
}
EOF


eval set -- $(getopt -o "da:ef:pvcr:x:" -l "debug,alias:,edit,function:,print,verbose,color,remove:,execute:" -- "$@")

option='print'
while [[ -n "$1" ]]; do
    case $1 in
        -d|--debug )
            PS4='$LINENO: '
            set -x;;
        -x|--execute )
            option='execute'
            shift
            WORD="$1";;
        -e|--edit )
            option='edit';;
        -f|--function )
            option='function'
            shift
            WORD="$1";;
        -p|--print )
            option="print";;
        -v|--verbose )
            verbose=true;;
        -c|--color )
            color=true;;
        -a|--alias )
            option='alias'
            shift
            WORD="$1";;
        -r|--remove )
            option='remove'
            shift
            WORD="$1";;
        -- )
            shift
            break;;
    esac
    shift
done


func_exists() {
    if [[ -f $LOCALALIAS_FILE ]]; then
        FUNC_EXISTS=$(cat $LOCALALIAS_FILE | grep -E "$WORD[ ]?\\(\\)")
    fi

    if [[ -n "$FUNC_EXISTS" ]]; then
        return 0
    else
        return 1
    fi
}

remove() {
    if func_exists; then
        sed -i "/$WORD ()/,/^$/d" $LOCALALIAS_FILE 2> /dev/null
    else
        sed -i "/$WORD=/d" $LOCALALIAS_FILE 2> /dev/null
    fi
}

add_alias() {
    printf "$WORD=''\033[1D" 
    IFS=
    read -n 1 C
    while [[ "$C" != "" ]]; do
        if [[ "$C" = "" ]]; then
            if [[ -n "$CMD" ]]; then
                CMD=${CMD::-1}
            fi
        else
            CMD="$CMD$C"
        fi

        echo -ne "\033[0K\r"
        echo -ne "\033[0K\r"  # 2nd call clears backspace character (^?)

        Q="'"
        if [[ "$CMD" == *"$Q"* ]]; then
            Q='"'
        fi

        printf "$WORD=$Q$CMD$Q\033[1D" 
        read -n 1 C
    done

    printf "alias $WORD=$Q$CMD$Q\n" >> $LOCALALIAS_FILE
    exit 0
}

add_function () {
    if [[ ! -s $LOCALALIAS_FILE ]]; then
        printf "$WORD () {}\n\n" > $LOCALALIAS_FILE
    else
        sed -i "1 i\\$WORD () {}\n" $LOCALALIAS_FILE
    fi
    vim -c "/$WORD () {\zs}\ze" -c 'normal n' +startinsert $LOCALALIAS_FILE
}

la_print () {
    if [[ -f $LOCALALIAS_FILE ]]; then
        if [ "$verbose" = true ]; then
            printf "\n========== Local Aliases ==========\n"
        fi

        if [[ -n "$1" ]]; then
            WORD=$1; shift
            if func_exists; then
                output=$(sed -n "/$WORD ()/,/^$/p" $LOCALALIAS_FILE)
            else
                output$(cat $LOCALALIAS_FILE | grep "alias $WORD.*=" | sort)
            fi
        else
            output=$(cat $LOCALALIAS_FILE)
        fi

        if [[ "$color" = true ]]; then
            echo "$output" | pygmentize -l sh
        else
            echo "$output"
        fi

        if [ "$verbose" = true ]; then
            echo
        fi
    else
        echo "$LOCALALIAS_FILE does not exist!"
        exit 1
    fi
}


case $option in
    'alias' )
        remove
        add_alias;;
    'function' )
        remove
        add_function;;
    'remove' )
        remove
        la_print;;
    'print' )
        la_print "$@";;
    'edit' )
        if [[ -n "$1" ]]; then
            WORD=$1; shift
            if func_exists; then
                vim -c "/$WORD ()" -c "normal nj^" $LOCALALIAS_FILE
            else
                vim -c "/$WORD=['\"]\zs.\ze" -c "normal n" $LOCALALIAS_FILE
            fi
        else
            vim $LOCALALIAS_FILE
        fi;;
    'execute' )
        DEF=$(grep -s "alias $WORD=" "$LOCALALIAS_FILE")
        CMD=${DEF/"alias $WORD="}; CMD=${CMD/#[\"\']}; CMD=${CMD/%[\"\']}

        if [[ "$CMD" == "@T "* ]]; then
            CMD="${CMD:3}"
            use_tmux=true
        fi

        if [ -n "$CMD" ]; then
            FINAL_CMD="$CMD $@"
        elif func_exists; then
            FINAL_CMD="$(awk -v my_func=$WORD -v args="$@" "$awkScript" $LOCALALIAS_FILE)"
        fi

        if [[ -n "$FINAL_CMD" ]]; then
            if [[ -n "$TMUX" ]] && [[ $use_tmux = true ]]; then
                tmux send-keys "$FINAL_CMD" "Enter"
            else
                /bin/zsh -c "$FINAL_CMD"
            fi
        else
            printf "Create a new local (a)lias/(f)unction for $WORD?: "
            read -n 1 CHOICE
            echo

            if [ "$CHOICE" == "a" ]; then
                add_alias
            elif [ "$CHOICE" == "f" ]; then
                add_function
            else
                exit 1
            fi

        fi;;
esac
