#!/bin/bash

# Allows me to have a .localaliases file in any directory that I want which
# can be used to customize bash commands locally.

SEP="="
DISPSEP=" ---> "

LocalAlias () {
    FILE="./.localaliases"
    ALIAS=$1
    GREP=$2
    ARGS="${@:3}"
    CMD=${GREP/"$ALIAS$SEP"}; CMD=${CMD/#[\"\']}; CMD=${CMD/%[\"\']}

    if [ -n "$CMD" ]; then
        printf "$ALIAS$DISPSEP$CMD $ARGS\n\n"
        eval "$CMD $ARGS"
        return 1
    else
        printf "Create a new local alias for $ALIAS? (y/n): "
        read -n 1 CHOICE
        echo

        if [ $CHOICE != "y" ]; then
            return 0
        fi

        printf "$ALIAS$DISPSEP"
        read CMD
        printf "$ALIAS$SEP\'$CMD\'\n" >> $FILE
        return 1
    fi
}
