name: lint
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r dev-requirements.txt

      - name: black
        run: |
          python -m black --check funky
          python -m black --check tests

      - name: isort
        run: |
          python -m isort --check-only funky
          python -m isort --check-only tests

      - name: flake8
        run: |
          python -m flake8 funky
          python -m flake8 tests

      - name: mypy
        run: |
          python -m mypy funky
          python -m mypy tests
